# Site settings
title: Subnero
description: > # this means to ignore newlines until "baseurl:"
  The future of underwater wireless.
url: " //localhost:4000" # the base hostname & protocol for your site
twitter_username: subnero
github_username:  subnero1
default_image: images/pulse-thumbnail-default.jpg

# Build settings
markdown: kramdown
encoding: UTF-8
highlighter: rouge
exclude: ["README.md", "**/README.md"]

